def Text(i, k, Pat):
    return (Pat[i:(i+k)])



def PatternCount(Texto, Pat):
    count = 0
    for i in range(len(Texto)-len(Pat)+1):
        if Text(i, len(Pat), Texto)==Pat :
            count +=1
    return count


string = 'CTGTCCATGGCTTGTCCAAGGGCTGTTGTCCAGCTGTCTGTCCACTGTCCAAGGATCCCTACGCTGTCCAGTACCTGTCCATCTGGAGCTGTCCACCCTGTCCACTTCTGTCCAGGCCACTGTCCATCACCACCAACTGTCCATACTGTCCATCTGTCCACGCGTAACTGTCCACCTGTCCAGATCTGTCGTCCAGAGCTGTCCATACTGTCCACTGTCCACTCTGTCCACGACTGTCCACTGTCCATGAGACTGTCCAGCCTGTCCACTGTCCACCTGTCCACTGTCCA'
look ='CTGTCCACT'

print(PatternCount(string, look))
